#
# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#
workspace(name = "bazel_demo_springboot_mvnjar")

maven_server(
    name = "default",
    url = "https://repo1.maven.org/maven2/",
)

# ---------------------------------------------
# Bazel version check
# Ensure people are running with a good-enough version of Bazel
# ---------------------------------------------

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "bazel_skylib",
    commit = "e59b620b392a8ebbcf25879fc3fde52b4dc77535",
    remote = "https://github.com/bazelbuild/bazel-skylib",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

versions.check("1.0.0")

# ---------------------------------------------
# Spring Boot Rule
# ---------------------------------------------

git_repository(
    name = "bazel_springboot_rule",
    remote = "https://github.com/salesforce/bazel-springboot-rule.git",
    commit = "ed5908c25487cd5806a5583006864cde8cf312a3",
)


# ---------------------------------------------
# External Dependencies
# ---------------------------------------------

maven_jar(
    name = "javax_annotation_javax_annotation_api",
    artifact = "javax.annotation:javax.annotation-api:1.3.2",
)

maven_jar(
    name = "junit_junit",
    artifact = "junit:junit:4.12",
    sha256 = "59721f0805e223d84b90677887d9ff567dc534d7c502ca903c0c2b17f05c116a",
    sha256_src = "9f43fea92033ad82bcad2ae44cec5c82abc9d6ee4b095cab921d11ead98bf2ff",
)

maven_jar(
    name = "ch_qos_logback_logback_classic",
    artifact = "ch.qos.logback:logback-classic:1.2.3",
)

maven_jar(
    name = "org_hamcrest_hamcrest_core",
    artifact = "org.hamcrest:hamcrest-core:1.3",
    sha256 = "66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9",
    sha256_src = "e223d2d8fbafd66057a8848cc94222d63c3cedd652cc48eddc0ab5c39c0f84df",
)

maven_jar(
    name = "org_slf4j_slf4j_api",
    artifact = "org.slf4j:slf4j-api:1.7.25",
    sha256 = "18c4a0095d5c1da6b817592e767bb23d29dd2f560ad74df75ff3961dbde25b79",
    sha256_src = "c4bc93180a4f0aceec3b057a2514abe04a79f06c174bbed910a2afb227b79366",
)

maven_jar(
    name = "org_slf4j_jul_to_slf4j",
    artifact = "org.slf4j:jul-to-slf4j:1.7.26",
)

maven_jar(
    name = "commons_logging_commons_logging",
    artifact = "commons-logging:commons-logging:1.2",
)

maven_jar(
    name = "org_apache_logging_log4j_log4j_to_slf4j",
    artifact = "org.apache.logging.log4j:log4j-to-slf4j:2.12.1",
    sha1 = "dfb42ea8ce1a399bcf7218efe8115a0b7ab3788a",
    sha1_src = "163f67b05f1c43ebb5204b9ef5f1e6767360cff0",
)

maven_jar(
    name = "org_apache_logging_log4j_log4j_api",
    artifact = "org.apache.logging.log4j:log4j-api:2.12.1",
    sha1 = "a55e6d987f50a515c9260b0451b4fa217dc539cb",
    sha1_src = "72dbe5460db61664f6bbfffb36665fa0bbe8e3ad",
)

maven_jar(
    name = "org_jboss_logging_jboss_logging",
    artifact = "org.jboss.logging:jboss-logging:3.4.1.Final",
)

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:20.0",
    sha256 = "36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8",
    sha256_src = "994be5933199a98e98bd09584da2bb69ed722275f6bed61d83459af88ace5cbd",
)

maven_jar(
    name = "ch_qos_logback_logback_core",
    artifact = "ch.qos.logback:logback-core:1.2.3",
    sha256 = "5946d837fe6f960c02a53eda7a6926ecc3c758bbdd69aa453ee429f858217f22",
    sha256_src = "1f69b6b638ec551d26b10feeade5a2b77abe347f9759da95022f0da9a63a9971",
)


# SPRING BOOT

maven_jar(
  name = "org_springframework_boot_spring_boot",
  artifact = "org.springframework.boot:spring-boot:2.2.1.RELEASE",
  sha1_src = "ac6d1512e0a854acf86b49a7fd0fecae04df4f08",
  sha1 = "3acb07ca9d6b968209a91aec6a7751f35bf22764",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_actuator",
  artifact = "org.springframework.boot:spring-boot-actuator:2.2.1.RELEASE",
  sha1 = "6f91f2e1f75b06388b65da9d3ae54164ad427922",
  sha1_src = "ec92a340bc384beb6a83b30e1d80a4594da6b90f",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_actuator_autoconfigure",
  artifact = "org.springframework.boot:spring-boot-actuator-autoconfigure:2.2.1.RELEASE",
  sha1 = "a6f0470d98405e7f2ca2ef418f2ef1b5f2695c53",
  sha1_src = "a109f93f7c3cb1493297e58fbcfd505748ef3920",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_autoconfigure",
  artifact = "org.springframework.boot:spring-boot-autoconfigure:2.2.1.RELEASE",
  sha1_src = "1d32cae2c4b6f09a22b32346320f1f0eeb1a3d48",
  sha1 = "1e45b519cc3b1de0b1ecee6eed6397c19ede95a2",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_configuration_processor",
  artifact = "org.springframework.boot:spring-boot-configuration-processor:2.2.1.RELEASE",
  sha1 = "95ba15dfcdde733c130a2813f9a5c93f7b9d01f0",
  sha1_src = "d23be822793fae472fef6af0c89202b6ba94d230",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_loader",
  artifact = "org.springframework.boot:spring-boot-loader:2.1.4.RELEASE",
  sha1 = "606e19c4c175399a5bad3e2e2f639ecee7ce3237",
  sha1_src = "0c325381230716538afb7a402eb090e367795074",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter",
  artifact = "org.springframework.boot:spring-boot-starter:2.2.1.RELEASE",
  sha1 = "5a4d687e6ffec805ce6320af7ca0b18798638200",
  sha1_src = "59509da18335073290c61afe3dc1ac7af4c54195",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_actuator",
  artifact = "org.springframework.boot:spring-boot-starter-actuator:2.1.4.RELEASE",
  sha1 = "3f3897febeecb4c3243e5a31bee769e4d9fd9445",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_freemarker",
  artifact = "org.springframework.boot:spring-boot-starter-freemarker:2.1.4.RELEASE",
  sha1 = "38fb2862111f6c3130b7255dc0d2ece759dc2c45",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_jdbc",
  artifact = "org.springframework.boot:spring-boot-starter-jdbc:2.1.4.RELEASE",
  sha1 = "1e5b6ff541d77655f3295d2f1d66f90f50b58f03",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_jetty",
  artifact = "org.springframework.boot:spring-boot-starter-jetty:2.1.4.RELEASE",
  sha1 = "091a4ce52a1792a35163b0487add255401de59e0",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_logging",
  artifact = "org.springframework.boot:spring-boot-starter-logging:2.2.1.RELEASE",
  sha1 = "8ba18bb64e02782065526e05bdd1ea5622b04b21",
  sha1_src = "df4ea87545b1ca478885ac41188b5fd925f2cca3",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_security",
  artifact = "org.springframework.boot:spring-boot-starter-security:2.1.4.RELEASE",
  sha1 = "07f8755a11498310510c223c1b4d6fb888561f2d",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_test",
  artifact = "org.springframework.boot:spring-boot-starter-test:2.1.4.RELEASE",
  sha1 = "6d19808f14c6d867eef42ea48bf78c37da1d6275",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_web",
  artifact = "org.springframework.boot:spring-boot-starter-web:2.1.4.RELEASE",
  sha1 = "a4659d55f57421a5ef122cb670b7b544ef8190e8",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_test",
  artifact = "org.springframework.boot:spring-boot-test:2.2.1.RELEASE",
  sha1_src = "b097a4aa5d3aaf5ed4ca93605865da1753de4345",
  sha1 = "e7eb297ce594e4b6d5185ab4004e460be4bf8d1a",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_test_autoconfigure",
  artifact = "org.springframework.boot:spring-boot-test-autoconfigure:2.2.1.RELEASE",
  sha1_src = "e873696d41d73a414b2b4d6c208794a00effda92",
  sha1 = "8724bfc256951048700ae2a6b0e62ba068f7e5e2",
)

maven_jar(
  name = "org_springframework_boot_spring_boot_starter_thymeleaf",
  artifact = "org.springframework.boot:spring-boot-starter-thymeleaf:2.1.4.RELEASE",
  sha1 = "631b7593129c2f8f43df783fc7fd4a0b5edce747",
)


# SPRING FRAMEWORK

maven_jar(
  name="org_springframework_plugin_spring_plugin_core",
  artifact="org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE",
  sha1="f380e7760032e7d929184f8ad8a33716b75c0657",
  sha1_src="112d82259202fa909d51cf7ccefae0c5523f1373",
)

maven_jar(
  name="org_springframework_plugin_spring_plugin_metadata",
  artifact="org.springframework.plugin:spring-plugin-metadata:jar:1.2.0.RELEASE",
  sha1="97223fc496b6cab31602eedbd4202aa4fff0d44f",
  sha1_src="6551604dd9c0619bae2f5a244580fa9a0dc646bf",
)

maven_jar(
  name = "org_springframework_retry_spring_retry",
  artifact = "org.springframework.retry:spring-retry:1.2.4.RELEASE",
  sha1 = "e5a1e629b2743dc7bbe4a8d07ebe9ff6c3b816ce",
  sha1_src = "26c0f619ab2af4ad6244e103fac42f327abcabbf",
)

maven_jar(
  name = "org_springframework_security_spring_security_config",
  artifact = "org.springframework.security:spring-security-config:5.2.1.RELEASE",
  sha1_src = "bbd406c763af685611698c5816eeb6cedcedc000",
  sha1 = "8f49e12035d0357b5f35e254334ea06d4585cf01",
)

maven_jar(
  name = "org_springframework_security_spring_security_core",
  artifact = "org.springframework.security:spring-security-core:5.2.1.RELEASE",
  sha1_src = "1ffd134e0a23a0564b44616daf401bbc7918275b",
  sha1 = "f1265ecdd4636a2038768c2ab9da4b79961a3465",
)

maven_jar(
  name = "org_springframework_security_spring_security_web",
  artifact = "org.springframework.security:spring-security-web:5.2.1.RELEASE",
  sha1_src = "44a612127342efee296f5a4c04004e6c0f622899",
  sha1 = "9e43c2d8d2dffc60bfba8ac95a106d30e9593106",
)

maven_jar(
  name = "org_springframework_spring_aop",
  artifact = "org.springframework:spring-aop:5.2.1.RELEASE",
  sha1 = "34c11ad92e06753e592865c7c403b09ab884d862",
  sha1_src = "37720d061b744366e1e1faf5aa6838df99f3ec47",
)

maven_jar(
  name = "org_springframework_spring_aspects",
  artifact = "org.springframework:spring-aspects:5.1.6.RELEASE",
  sha1_src = "668bbfa9d2b1c53536904910949b8013a1e57af6",
  sha1 = "c17785ecb504e026dd910facc44127db6317577a",
)

maven_jar(
  name = "org_springframework_spring_beans",
  artifact = "org.springframework:spring-beans:5.2.1.RELEASE",
  sha1_src = "d2a036b0652391aa91828b00e87f9354822a2e70",
  sha1 = "d05690257d8e8034b180db3893d5baf8250fb9d3",
)

maven_jar(
  name = "org_springframework_spring_context",
  artifact = "org.springframework:spring-context:5.2.1.RELEASE",
  sha1_src = "43da4e562e25c4c5931e2dec04f2037f9d230391",
  sha1 = "1d3e142adbdbd0810b19462fbd88d94cc51cce01",
)

maven_jar(
  name = "org_springframework_spring_context_support",
  artifact = "org.springframework:spring-context-support:5.2.1.RELEASE",
  sha1_src = "51bbd8974243c7fd29ee6ec7c3807cdbc5b1be2d",
  sha1 = "22fedda999e1b443be19bc3fb7ec326a6e0caf05",
)

maven_jar(
  name = "org_springframework_spring_core",
  artifact = "org.springframework:spring-core:5.2.1.RELEASE",
  sha1_src = "55e7202309d932c4d47ccec00500f98425406309",
  sha1 = "32b265ff5c7c35257b5a242b9628dcd321a2b010",
)

maven_jar(
  name = "org_springframework_spring_expression",
  artifact = "org.springframework:spring-expression:5.2.1.RELEASE",
  sha1_src = "0896e15320e8e21b87e93622d984e0afc52fdb26",
  sha1 = "499e91096320f7e6fcfd6920e66d5ed5f0ecfee9",
)

maven_jar(
  name = "org_springframework_spring_jdbc",
  artifact = "org.springframework:spring-jdbc:5.2.1.RELEASE",
  sha1_src = "5b790943095dbb4c26a43d00415be88c8e8bbae1",
  sha1 = "b33c907cbaff98fdfe7d8707ce046e595805c795",
)

maven_jar(
  name = "org_springframework_spring_test",
  artifact = "org.springframework:spring-test:5.2.1.RELEASE",
  sha1 = "939bbeb098b3944f3f5323d6c3703cb9b78f5de2",
  sha1_src = "628dee8555b5010b926ebd880f7b108140520c71",
)

maven_jar(
  name = "org_springframework_spring_tx",
  artifact = "org.springframework:spring-tx:5.2.1.RELEASE",
  sha1_src = "0e13efee00643e55716f214a22e4f6a8fb8e3817",
  sha1 = "eea31b77780487a188af44d9a1bacf717a68da72",
)

maven_jar(
  name = "org_springframework_spring_web",
  artifact = "org.springframework:spring-web:5.2.1.RELEASE",
  sha1 = "4f1dfe592951c312b52de469f1940b1cb0455226",
  sha1_src = "5247d73874757aa411626d2bf156360768005dc5",
)

maven_jar(
  name = "org_springframework_spring_webmvc",
  artifact = "org.springframework:spring-webmvc:5.2.1.RELEASE",
  sha1 = "9c118e3a551fe4bf31eb9e395b5f8ef42cf14f42",
  sha1_src = "3668f11c423b5fa6d442a0282151895dc81959ca",
)


# Jetty

maven_jar(
    name = "org_eclipse_jetty_jetty_http",
    artifact = "org.eclipse.jetty:jetty-http:9.4.22.v20191022",
)

maven_jar(
    name = "org_eclipse_jetty_jetty_io",
    artifact = "org.eclipse.jetty:jetty-io:9.4.22.v20191022",
)

maven_jar(
    name = "org_eclipse_jetty_jetty_security",
    artifact = "org.eclipse.jetty:jetty-security:9.4.22.v20191022",
)

maven_jar(
    name = "org_eclipse_jetty_jetty_server",
    artifact = "org.eclipse.jetty:jetty-server:9.4.22.v20191022",
)

maven_jar(
    name = "org_eclipse_jetty_jetty_servlet",
    artifact = "org.eclipse.jetty:jetty-servlet:9.4.22.v20191022",
)

maven_jar(
    name = "org_eclipse_jetty_jetty_util",
    artifact = "org.eclipse.jetty:jetty-util:9.4.22.v20191022",
)

maven_jar(
    name = "org_eclipse_jetty_jetty_webapp",
    artifact = "org.eclipse.jetty:jetty-webapp:9.4.22.v20191022",
)

maven_jar(
    name = "javax_servlet_javax_servlet_api",
    artifact = "javax.servlet:javax.servlet-api:4.0.1",
)


# Jackson

maven_jar(
    name = "com_fasterxml_classmate",
    artifact = "com.fasterxml:classmate:1.5.1",
    sha1_src = "504edac38ff03cc5ce1d0391abb1416ffad58a99",
    sha1 = "3fe0bed568c62df5e89f4f174c101eab25345b6c",
)

maven_jar(
    name = "com_fasterxml_jackson_core_jackson_annotations",
    artifact = "com.fasterxml.jackson.core:jackson-annotations:2.10.0",
    sha1 = "d88d5a15951ffcf8ddd5766f5170a45de537b284",
    sha1_src = "c8be836b340e2bf48c335cfd68765ab867cfd088",
)

maven_jar(
    name = "com_fasterxml_jackson_core_jackson_core",
    artifact = "com.fasterxml.jackson.core:jackson-core:2.10.0",
    sha1 = "4e2c5fa04648ec9772c63e2101c53af6504e624e",
    sha1_src = "379d754e510e25111a823428636be68773fc73c9",
)

maven_jar(
    name = "com_fasterxml_jackson_core_jackson_databind",
    artifact = "com.fasterxml.jackson.core:jackson-databind:2.10.0",
    sha1 = "1127c9cf62f2bb3121a3a2a0a1351d251a602117",
    sha1_src = "465988edbcc098cebd769e2ef110ce57661a27a4",
)

maven_jar(
    name = "com_fasterxml_jackson_datatype_jackson_datatype_jdk8",
    artifact = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.10.0",
    sha1_src = "7e77a5a26a7a3e293faaf8d4391d8248406cbbe2",
    sha1 = "ac9b5e4ec02f243c580113c0c58564d90432afaa",
)

maven_jar(
    name = "com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
    artifact = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.0",
    sha1 = "946bcb4b3ba9facfb338b1d48c2606225205a70c",
    sha1_src = "fa7bb655432311553c9717ef01d1b12989db4090",
)

maven_jar(
    name = "com_fasterxml_jackson_module_jackson_module_parameter_names",
    artifact = "com.fasterxml.jackson.module:jackson-module-parameter-names:2.10.0",
    sha1 = "d7ae5421ab27486429aeb878b7e3937544d9324a",
    sha1_src = "a52ab29f26c0b5b10b18584971ab78811e0dae0e",
)
