#
# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#
workspace(name = "bazel_demo_proto_java")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")


# ---------------------------------------------
# Bazel version check
# Ensure people are running with a good-enough version of Bazel
# ---------------------------------------------

http_archive(
    name = "bazel_skylib",
    sha256 = "c6966ec828da198c5d9adbaa94c05e3a1c7f21bd012a0b29ba8ddbccb2c93b0d",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz",
    ],
)
load("@bazel_skylib//lib:versions.bzl", "versions")
versions.check("4.2.1")

# ---------------------------------------------
# External Dependencies
# ---------------------------------------------

RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")
rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")
rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
      artifacts = [
        "ch.qos.logback:logback-core:1.2.3",
        "com.google.guava:guava:20.0",
        "junit:junit:4.12",
        "org.hamcrest:hamcrest-core:1.3",
        "org.slf4j:slf4j-api:1.7.25",
      ],
      repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
      ],
      fetch_sources = True,
      version_conflict_policy = 'pinned',
      strict_visibility = True,
      generate_compat_repositories = False,
  )

# ZLIB (for protobuf)
# Copied from zlib_net https://github.com/grpc/grpc-java/blob/v1.24.x/repositories.bzl
local_repository(
    name = "zlib",
    path = "tools/zlib/zlib-1.2.11",
)

# PROTOBUF
# proto_library, cc_proto_library, java_proto_library, and kt_jvm_proto_library rules
# implicitly depend on @com_google_protobuf for protoc and proto runtimes.
# This statement defines the @com_google_protobuf repo and allows us to explicitly
# control what version of protobuf we use (rather than allowing rules_proto to
# control it)
http_archive(
    name = "com_google_protobuf",
    sha256 = "25680843adf0c3302648d35f744e38cc3b6b05a6c77a927de5aea3e1c2e36106",
    strip_prefix = "protobuf-3.19.4",
    urls = [
        "https://github.com/protocolbuffers/protobuf/archive/v3.19.4.zip",
    ],
)

# PROTOBUF
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

http_archive(
    name = "rules_proto",
    sha256 = "66bfdf8782796239d3875d37e7de19b1d94301e8972b3cbd2446b332429b4df1",
    strip_prefix = "rules_proto-4.0.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()
