#
# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root  or https://opensource.org/licenses/BSD-3-Clause
#
workspace(name = "bazel_demo_simplejava_mvnimport")

# ---------------------------------------------
# Bazel version check
# Ensure people are running with a good-enough version of Bazel
# ---------------------------------------------

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "bazel_skylib",
    commit = "e59b620b392a8ebbcf25879fc3fde52b4dc77535",
    remote = "https://github.com/bazelbuild/bazel-skylib",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

versions.check("2.2.0")

# ---------------------------------------------
# External Dependencies
# ---------------------------------------------

load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

mvn_server_urls = ["https://repo1.maven.org/maven2/"]
fetch_sources = True

jvm_maven_import_external(
  name = "junit_junit",
  artifact = "junit:junit:4.12",
  artifact_sha256 = "59721f0805e223d84b90677887d9ff567dc534d7c502ca903c0c2b17f05c116a",
  srcjar_sha256 = "9f43fea92033ad82bcad2ae44cec5c82abc9d6ee4b095cab921d11ead98bf2ff",
  server_urls = mvn_server_urls,
  fetch_sources = fetch_sources,
)

jvm_maven_import_external(
  name = "org_hamcrest_hamcrest_core",
  artifact = "org.hamcrest:hamcrest-core:1.3",
  artifact_sha256 = "66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9",
  srcjar_sha256 = "e223d2d8fbafd66057a8848cc94222d63c3cedd652cc48eddc0ab5c39c0f84df",
  server_urls = mvn_server_urls,
  fetch_sources = fetch_sources,
)

jvm_maven_import_external(
  name = "org_slf4j_slf4j_api",
  artifact = "org.slf4j:slf4j-api:1.7.30",
  artifact_sha256 = "cdba07964d1bb40a0761485c6b1e8c2f8fd9eb1d19c53928ac0d7f9510105c57",
  srcjar_sha256 = "9ee459644577590fed7ea94afae781fa3cc9311d4553faee8a3219ffbd7cc386",
  server_urls = mvn_server_urls,
  fetch_sources = fetch_sources,
)

jvm_maven_import_external(
  name = "com_google_guava_guava",
  artifact = "com.google.guava:guava:26.0-sfdc2",
  artifact_sha256 = "069518804d5d104ba75031c0509d15babbf1f8e48e5532d18e7b8bfc53ebb596",
  srcjar_sha256 = "d436899ed36876c2badc216f115ad5422da32c25d8462444b06c82fe0e0c46f6",
  server_urls = mvn_server_urls,
  fetch_sources = fetch_sources,
)

jvm_maven_import_external(
  name = "ch_qos_logback_logback_core",
  artifact = "ch.qos.logback:logback-core:1.2.3",
  artifact_sha256 = "5946d837fe6f960c02a53eda7a6926ecc3c758bbdd69aa453ee429f858217f22",
  srcjar_sha256 = "1f69b6b638ec551d26b10feeade5a2b77abe347f9759da95022f0da9a63a9971",
  server_urls = mvn_server_urls,
  fetch_sources = fetch_sources,
)
